// SPDX-FileCopyrightText: 2026 Andrei Podkovyrin
// SPDX-License-Identifier: MIT

#pragma once

#include "detail.hpp"

namespace spoken_time::detail {
inline constexpr Words nl = {
    "nul",           "één",          "twee",           "drie",          "vier",
    "vijf",          "zes",          "zeven",          "acht",          "negen",
    "tien",          "elf",          "twaalf",         "dertien",       "veertien",
    "vijftien",      "zestien",      "zeventien",      "achttien",      "negentien",
    "twintig",       "eenentwintig", "tweeëntwintig",  "drieëntwintig", "vierentwintig",
    "vijfentwintig", "zesentwintig", "zevenentwintig", "achtentwintig", "negenentwintig"};
inline constexpr Words de = {"null",
                             "eins",
                             "zwei",
                             "drei",
                             "vier",
                             "fünf",
                             "sechs",
                             "sieben",
                             "acht",
                             "neun",
                             "zehn",
                             "elf",
                             "zwölf",
                             "dreizehn",
                             "vierzehn",
                             "fünfzehn",
                             "sechzehn",
                             "siebzehn",
                             "achtzehn",
                             "neunzehn",
                             "zwanzig",
                             "einundzwanzig",
                             "zweiundzwanzig",
                             "dreiundzwanzig",
                             "vierundzwanzig",
                             "fünfundzwanzig",
                             "sechsundzwanzig",
                             "siebenundzwanzig",
                             "achtundzwanzig",
                             "neunundzwanzig"};
inline constexpr Words en = {
    "zero",        "one",         "two",        "three",        "four",         "five",
    "six",         "seven",       "eight",      "nine",         "ten",          "eleven",
    "twelve",      "thirteen",    "fourteen",   "fifteen",      "sixteen",      "seventeen",
    "eighteen",    "nineteen",    "twenty",     "twenty-one",   "twenty-two",   "twenty-three",
    "twenty-four", "twenty-five", "twenty-six", "twenty-seven", "twenty-eight", "twenty-nine"};
inline constexpr Words da = {"nul",       "et",         "to",        "tre",        "fire",
                             "fem",       "seks",       "syv",       "otte",       "ni",
                             "ti",        "elleve",     "tolv",      "tretten",    "fjorten",
                             "femten",    "seksten",    "sytten",    "atten",      "nitten",
                             "tyve",      "enogtyve",   "toogtyve",  "treogtyve",  "fireogtyve",
                             "femogtyve", "seksogtyve", "syvogtyve", "otteogtyve", "niogtyve"};
inline constexpr Words nb = {"null",     "ett",     "to",       "tre",     "fire",     "fem",
                             "seks",     "sju",     "åtte",     "ni",      "ti",       "elleve",
                             "tolv",     "tretten", "fjorten",  "femten",  "seksten",  "sytten",
                             "atten",    "nitten",  "tjue",     "tjueen",  "tjueto",   "tjuetre",
                             "tjuefire", "tjuefem", "tjueseks", "tjuesju", "tjueåtte", "tjueni"};
inline constexpr Words sv = {"noll",     "ett",      "två",      "tre",       "fyra",
                             "fem",      "sex",      "sju",      "åtta",      "nio",
                             "tio",      "elva",     "tolv",     "tretton",   "fjorton",
                             "femton",   "sexton",   "sjutton",  "arton",     "nitton",
                             "tjugo",    "tjugoett", "tjugotvå", "tjugotre",  "tjugofyra",
                             "tjugofem", "tjugosex", "tjugosju", "tjugoåtta", "tjugonio"};
inline constexpr Words is = {"núll",
                             "eitt",
                             "tvö",
                             "þrjú",
                             "fjögur",
                             "fimm",
                             "sex",
                             "sjö",
                             "átta",
                             "níu",
                             "tíu",
                             "ellefu",
                             "tólf",
                             "þrettán",
                             "fjórtán",
                             "fimmtán",
                             "sextán",
                             "sautján",
                             "átján",
                             "nítján",
                             "tuttugu",
                             "tuttugu og eitt",
                             "tuttugu og tvö",
                             "tuttugu og þrjú",
                             "tuttugu og fjögur",
                             "tuttugu og fimm",
                             "tuttugu og sex",
                             "tuttugu og sjö",
                             "tuttugu og átta",
                             "tuttugu og níu"};
inline constexpr Words fi = {"nolla",
                             "yksi",
                             "kaksi",
                             "kolme",
                             "neljä",
                             "viisi",
                             "kuusi",
                             "seitsemän",
                             "kahdeksan",
                             "yhdeksän",
                             "kymmenen",
                             "yksitoista",
                             "kaksitoista",
                             "kolmetoista",
                             "neljätoista",
                             "viisitoista",
                             "kuusitoista",
                             "seitsemäntoista",
                             "kahdeksantoista",
                             "yhdeksäntoista",
                             "kaksikymmentä",
                             "kaksikymmentäyksi",
                             "kaksikymmentäkaksi",
                             "kaksikymmentäkolme",
                             "kaksikymmentäneljä",
                             "kaksikymmentäviisi",
                             "kaksikymmentäkuusi",
                             "kaksikymmentäseitsemän",
                             "kaksikymmentäkahdeksan",
                             "kaksikymmentäyhdeksän"};
inline constexpr Words et = {"null",
                             "üks",
                             "kaks",
                             "kolm",
                             "neli",
                             "viis",
                             "kuus",
                             "seitse",
                             "kaheksa",
                             "üheksa",
                             "kümme",
                             "üksteist",
                             "kaksteist",
                             "kolmteist",
                             "neliteist",
                             "viisteist",
                             "kuusteist",
                             "seitseteist",
                             "kaheksateist",
                             "üheksateist",
                             "kakskümmend",
                             "kakskümmend üks",
                             "kakskümmend kaks",
                             "kakskümmend kolm",
                             "kakskümmend neli",
                             "kakskümmend viis",
                             "kakskümmend kuus",
                             "kakskümmend seitse",
                             "kakskümmend kaheksa",
                             "kakskümmend üheksa"};
inline constexpr Words fr = {
    "zéro",         "un",         "deux",      "trois",       "quatre",     "cinq",
    "six",          "sept",       "huit",      "neuf",        "dix",        "onze",
    "douze",        "treize",     "quatorze",  "quinze",      "seize",      "dix-sept",
    "dix-huit",     "dix-neuf",   "vingt",     "vingt et un", "vingt-deux", "vingt-trois",
    "vingt-quatre", "vingt-cinq", "vingt-six", "vingt-sept",  "vingt-huit", "vingt-neuf"};
inline constexpr Words es = {
    "cero",         "uno",         "dos",        "tres",        "cuatro",     "cinco",
    "seis",         "siete",       "ocho",       "nueve",       "diez",       "once",
    "doce",         "trece",       "catorce",    "quince",      "dieciséis",  "diecisiete",
    "dieciocho",    "diecinueve",  "veinte",     "veintiuno",   "veintidós",  "veintitrés",
    "veinticuatro", "veinticinco", "veintiséis", "veintisiete", "veintiocho", "veintinueve"};
inline constexpr Words pt = {
    "zero",          "um",           "dois",         "três",         "quatro",
    "cinco",         "seis",         "sete",         "oito",         "nove",
    "dez",           "onze",         "doze",         "treze",        "catorze",
    "quinze",        "dezasseis",    "dezassete",    "dezoito",      "dezanove",
    "vinte",         "vinte e um",   "vinte e dois", "vinte e três", "vinte e quatro",
    "vinte e cinco", "vinte e seis", "vinte e sete", "vinte e oito", "vinte e nove"};
inline constexpr Words it = {"zero",        "uno",      "due",         "tre",      "quattro",
                             "cinque",      "sei",      "sette",       "otto",     "nove",
                             "dieci",       "undici",   "dodici",      "tredici",  "quattordici",
                             "quindici",    "sedici",   "diciassette", "diciotto", "diciannove",
                             "venti",       "ventuno",  "ventidue",    "ventitré", "ventiquattro",
                             "venticinque", "ventisei", "ventisette",  "ventotto", "ventinove"};
inline constexpr Words ro = {"zero",
                             "unu",
                             "două",
                             "trei",
                             "patru",
                             "cinci",
                             "șase",
                             "șapte",
                             "opt",
                             "nouă",
                             "zece",
                             "unsprezece",
                             "douăsprezece",
                             "treisprezece",
                             "paisprezece",
                             "cincisprezece",
                             "șaisprezece",
                             "șaptesprezece",
                             "optsprezece",
                             "nouăsprezece",
                             "douăzeci",
                             "douăzeci și unu",
                             "douăzeci și două",
                             "douăzeci și trei",
                             "douăzeci și patru",
                             "douăzeci și cinci",
                             "douăzeci și șase",
                             "douăzeci și șapte",
                             "douăzeci și opt",
                             "douăzeci și nouă"};
inline constexpr Words ca = {
    "zero",          "un",          "dos",        "tres",       "quatre",      "cinc",
    "sis",           "set",         "vuit",       "nou",        "deu",         "onze",
    "dotze",         "tretze",      "catorze",    "quinze",     "setze",       "disset",
    "divuit",        "dinou",       "vint",       "vint-i-un",  "vint-i-dos",  "vint-i-tres",
    "vint-i-quatre", "vint-i-cinc", "vint-i-sis", "vint-i-set", "vint-i-vuit", "vint-i-nou"};
inline constexpr Words cs = {
    "nula",         "jedna",      "dvě",         "tři",          "čtyři",      "pět",
    "šest",         "sedm",       "osm",         "devět",        "deset",      "jedenáct",
    "dvanáct",      "třináct",    "čtrnáct",     "patnáct",      "šestnáct",   "sedmnáct",
    "osmnáct",      "devatenáct", "dvacet",      "dvacet jedna", "dvacet dvě", "dvacet tři",
    "dvacet čtyři", "dvacet pět", "dvacet šest", "dvacet sedm",  "dvacet osm", "dvacet devět"};
inline constexpr Words sk = {
    "nula",         "jedna",      "dve",         "tri",          "štyri",       "päť",
    "šesť",         "sedem",      "osem",        "deväť",        "desať",       "jedenásť",
    "dvanásť",      "trinásť",    "štrnásť",     "pätnásť",      "šestnásť",    "sedemnásť",
    "osemnásť",     "devätnásť",  "dvadsať",     "dvadsaťjedna", "dvadsaťdve",  "dvadsaťtri",
    "dvadsaťštyri", "dvadsaťpäť", "dvadsaťšesť", "dvadsaťsedem", "dvadsaťosem", "dvadsaťdeväť"};
inline constexpr Words sl = {"nič",
                             "ena",
                             "dve",
                             "tri",
                             "štiri",
                             "pet",
                             "šest",
                             "sedem",
                             "osem",
                             "devet",
                             "deset",
                             "enajst",
                             "dvanajst",
                             "trinajst",
                             "štirinajst",
                             "petnajst",
                             "šestnajst",
                             "sedemnajst",
                             "osemnajst",
                             "devetnajst",
                             "dvajset",
                             "enindvajset",
                             "dvaindvajset",
                             "triindvajset",
                             "štiriindvajset",
                             "petindvajset",
                             "šestindvajset",
                             "sedemindvajset",
                             "osemindvajset",
                             "devetindvajset"};
inline constexpr Words sh = {"nula",
                             "jedan",
                             "dva",
                             "tri",
                             "četiri",
                             "pet",
                             "šest",
                             "sedam",
                             "osam",
                             "devet",
                             "deset",
                             "jedanaest",
                             "dvanaest",
                             "trinaest",
                             "četrnaest",
                             "petnaest",
                             "šesnaest",
                             "sedamnaest",
                             "osamnaest",
                             "devetnaest",
                             "dvadeset",
                             "dvadeset i jedan",
                             "dvadeset i dva",
                             "dvadeset i tri",
                             "dvadeset i četiri",
                             "dvadeset i pet",
                             "dvadeset i šest",
                             "dvadeset i sedam",
                             "dvadeset i osam",
                             "dvadeset i devet"};
inline constexpr Words bg = {"нула",
                             "един",
                             "два",
                             "три",
                             "четири",
                             "пет",
                             "шест",
                             "седем",
                             "осем",
                             "девет",
                             "десет",
                             "единадесет",
                             "дванадесет",
                             "тринадесет",
                             "четиринадесет",
                             "петнадесет",
                             "шестнадесет",
                             "седемнадесет",
                             "осемнадесет",
                             "деветнадесет",
                             "двадесет",
                             "двадесет и един",
                             "двадесет и два",
                             "двадесет и три",
                             "двадесет и четири",
                             "двадесет и пет",
                             "двадесет и шест",
                             "двадесет и седем",
                             "двадесет и осем",
                             "двадесет и девет"};
inline constexpr Words ru = {"ноль",
                             "один",
                             "два",
                             "три",
                             "четыре",
                             "пять",
                             "шесть",
                             "семь",
                             "восемь",
                             "девять",
                             "десять",
                             "одиннадцать",
                             "двенадцать",
                             "тринадцать",
                             "четырнадцать",
                             "пятнадцать",
                             "шестнадцать",
                             "семнадцать",
                             "восемнадцать",
                             "девятнадцать",
                             "двадцать",
                             "двадцать один",
                             "двадцать два",
                             "двадцать три",
                             "двадцать четыре",
                             "двадцать пять",
                             "двадцать шесть",
                             "двадцать семь",
                             "двадцать восемь",
                             "двадцать девять"};
inline constexpr Words uk = {"нуль",
                             "один",
                             "два",
                             "три",
                             "чотири",
                             "п’ять",
                             "шість",
                             "сім",
                             "вісім",
                             "дев’ять",
                             "десять",
                             "одинадцять",
                             "дванадцять",
                             "тринадцять",
                             "чотирнадцять",
                             "п’ятнадцять",
                             "шістнадцять",
                             "сімнадцять",
                             "вісімнадцять",
                             "дев’ятнадцять",
                             "двадцять",
                             "двадцять один",
                             "двадцять два",
                             "двадцять три",
                             "двадцять чотири",
                             "двадцять п’ять",
                             "двадцять шість",
                             "двадцять сім",
                             "двадцять вісім",
                             "двадцять дев’ять"};
inline constexpr Words pl = {"zero",
                             "jeden",
                             "dwie",
                             "trzy",
                             "cztery",
                             "pięć",
                             "sześć",
                             "siedem",
                             "osiem",
                             "dziewięć",
                             "dziesięć",
                             "jedenaście",
                             "dwanaście",
                             "trzynaście",
                             "czternaście",
                             "piętnaście",
                             "szesnaście",
                             "siedemnaście",
                             "osiemnaście",
                             "dziewiętnaście",
                             "dwadzieścia",
                             "dwadzieścia jeden",
                             "dwadzieścia dwie",
                             "dwadzieścia trzy",
                             "dwadzieścia cztery",
                             "dwadzieścia pięć",
                             "dwadzieścia sześć",
                             "dwadzieścia siedem",
                             "dwadzieścia osiem",
                             "dwadzieścia dziewięć"};
inline constexpr Words hu = {"nulla",    "egy",       "kettő",       "három",       "négy",
                             "öt",       "hat",       "hét",         "nyolc",       "kilenc",
                             "tíz",      "tizenegy",  "tizenkettő",  "tizenhárom",  "tizennégy",
                             "tizenöt",  "tizenhat",  "tizenhét",    "tizennyolc",  "tizenkilenc",
                             "húsz",     "huszonegy", "huszonkettő", "huszonhárom", "huszonnégy",
                             "huszonöt", "huszonhat", "huszonhét",   "huszonnyolc", "huszonkilenc"};
inline constexpr Words tr = {"sıfır",     "bir",        "iki",        "üç",          "dört",
                             "beş",       "altı",       "yedi",       "sekiz",       "dokuz",
                             "on",        "on bir",     "on iki",     "on üç",       "on dört",
                             "on beş",    "on altı",    "on yedi",    "on sekiz",    "on dokuz",
                             "yirmi",     "yirmi bir",  "yirmi iki",  "yirmi üç",    "yirmi dört",
                             "yirmi beş", "yirmi altı", "yirmi yedi", "yirmi sekiz", "yirmi dokuz"};
inline constexpr Words sq = {"zero",
                             "një",
                             "dy",
                             "tre",
                             "katër",
                             "pesë",
                             "gjashtë",
                             "shtatë",
                             "tetë",
                             "nëntë",
                             "dhjetë",
                             "njëmbëdhjetë",
                             "dymbëdhjetë",
                             "trembëdhjetë",
                             "katërmbëdhjetë",
                             "pesëmbëdhjetë",
                             "gjashtëmbëdhjetë",
                             "shtatëmbëdhjetë",
                             "tetëmbëdhjetë",
                             "nëntëmbëdhjetë",
                             "njëzet",
                             "njëzet e një",
                             "njëzet e dy",
                             "njëzet e tre",
                             "njëzet e katër",
                             "njëzet e pesë",
                             "njëzet e gjashtë",
                             "njëzet e shtatë",
                             "njëzet e tetë",
                             "njëzet e nëntë"};
inline constexpr Words eu = {"zero",
                             "bat",
                             "bi",
                             "hiru",
                             "lau",
                             "bost",
                             "sei",
                             "zazpi",
                             "zortzi",
                             "bederatzi",
                             "hamar",
                             "hamaika",
                             "hamabi",
                             "hamahiru",
                             "hamalau",
                             "hamabost",
                             "hamasei",
                             "hamazazpi",
                             "hamazortzi",
                             "hemeretzi",
                             "hogei",
                             "hogeita bat",
                             "hogeita bi",
                             "hogeita hiru",
                             "hogeita lau",
                             "hogeita bost",
                             "hogeita sei",
                             "hogeita zazpi",
                             "hogeita zortzi",
                             "hogeita bederatzi"};
inline constexpr Words el = {
    "μηδέν",        "ένα",        "δύο",         "τρία",        "τέσσερα",
    "πέντε",        "έξι",        "επτά",        "οκτώ",        "εννέα",
    "δέκα",         "έντεκα",     "δώδεκα",      "δεκατρία",    "δεκατέσσερα",
    "δεκαπέντε",    "δεκαέξι",    "δεκαεπτά",    "δεκαοκτώ",    "δεκαεννέα",
    "είκοσι",       "είκοσι ένα", "είκοσι δύο",  "είκοσι τρία", "είκοσι τέσσερα",
    "είκοσι πέντε", "είκοσι έξι", "είκοσι επτά", "είκοσι οκτώ", "είκοσι εννέα"};
inline constexpr Words lv = {"nulle",
                             "viens",
                             "divi",
                             "trīs",
                             "četri",
                             "pieci",
                             "seši",
                             "septiņi",
                             "astoņi",
                             "deviņi",
                             "desmit",
                             "vienpadsmit",
                             "divpadsmit",
                             "trīspadsmit",
                             "četrpadsmit",
                             "piecpadsmit",
                             "sešpadsmit",
                             "septiņpadsmit",
                             "astoņpadsmit",
                             "deviņpadsmit",
                             "divdesmit",
                             "divdesmit viens",
                             "divdesmit divi",
                             "divdesmit trīs",
                             "divdesmit četri",
                             "divdesmit pieci",
                             "divdesmit seši",
                             "divdesmit septiņi",
                             "divdesmit astoņi",
                             "divdesmit deviņi"};
inline constexpr Words lt = {"nulis",
                             "viena",
                             "dvi",
                             "trys",
                             "keturios",
                             "penkios",
                             "šešios",
                             "septynios",
                             "aštuonios",
                             "devynios",
                             "dešimt",
                             "vienuolika",
                             "dvylika",
                             "trylika",
                             "keturiolika",
                             "penkiolika",
                             "šešiolika",
                             "septyniolika",
                             "aštuoniolika",
                             "devyniolika",
                             "dvidešimt",
                             "dvidešimt viena",
                             "dvidešimt dvi",
                             "dvidešimt trys",
                             "dvidešimt keturios",
                             "dvidešimt penkios",
                             "dvidešimt šešios",
                             "dvidešimt septynios",
                             "dvidešimt aštuonios",
                             "dvidešimt devynios"};
inline constexpr Words mt = {"żero",
                             "wieħed",
                             "tnejn",
                             "tlieta",
                             "erbgħa",
                             "ħamsa",
                             "sitta",
                             "sebgħa",
                             "tmienja",
                             "disgħa",
                             "għaxra",
                             "ħdax",
                             "tnax",
                             "tlettax",
                             "erbatax",
                             "ħmistax",
                             "sittax",
                             "sbatax",
                             "tmintax",
                             "dsatax",
                             "għoxrin",
                             "wieħed u għoxrin",
                             "tnejn u għoxrin",
                             "tlieta u għoxrin",
                             "erbgħa u għoxrin",
                             "ħamsa u għoxrin",
                             "sitta u għoxrin",
                             "sebgħa u għoxrin",
                             "tmienja u għoxrin",
                             "disgħa u għoxrin"};
inline constexpr Words ga = {"náid",
                             "aon",
                             "dó",
                             "trí",
                             "ceathair",
                             "cúig",
                             "sé",
                             "seacht",
                             "ocht",
                             "naoi",
                             "deich",
                             "aon déag",
                             "dó dhéag",
                             "trí déag",
                             "ceathair déag",
                             "cúig déag",
                             "sé déag",
                             "seacht déag",
                             "ocht déag",
                             "naoi déag",
                             "fiche",
                             "aon is fiche",
                             "dó is fiche",
                             "trí is fiche",
                             "ceathair is fiche",
                             "cúig is fiche",
                             "sé is fiche",
                             "seacht is fiche",
                             "ocht is fiche",
                             "naoi is fiche"};
inline constexpr Words gd = {"neoni",
                             "aon",
                             "dà",
                             "trì",
                             "ceithir",
                             "còig",
                             "sia",
                             "seachd",
                             "ochd",
                             "naoi",
                             "deich",
                             "aon deug",
                             "dà dheug",
                             "trì deug",
                             "ceithir deug",
                             "còig deug",
                             "sia deug",
                             "seachd deug",
                             "ochd deug",
                             "naoi deug",
                             "fichead",
                             "aon air fhichead",
                             "dà air fhichead",
                             "trì air fhichead",
                             "ceithir air fhichead",
                             "còig air fhichead",
                             "sia air fhichead",
                             "seachd air fhichead",
                             "ochd air fhichead",
                             "naoi air fhichead"};
inline constexpr Words cy = {"sero",
                             "un",
                             "dau",
                             "tri",
                             "pedwar",
                             "pump",
                             "chwech",
                             "saith",
                             "wyth",
                             "naw",
                             "deg",
                             "un ar ddeg",
                             "deuddeg",
                             "tri ar ddeg",
                             "pedwar ar ddeg",
                             "pymtheg",
                             "un ar bymtheg",
                             "dau ar bymtheg",
                             "deunaw",
                             "pedwar ar bymtheg",
                             "ugain",
                             "un ar hugain",
                             "dau ar hugain",
                             "tri ar hugain",
                             "pedwar ar hugain",
                             "pump ar hugain",
                             "chwech ar hugain",
                             "saith ar hugain",
                             "wyth ar hugain",
                             "naw ar hugain"};
inline constexpr Words br = {"mann",
                             "unan",
                             "daou",
                             "tri",
                             "pevar",
                             "pemp",
                             "c'hwec'h",
                             "seizh",
                             "eizh",
                             "nav",
                             "dek",
                             "unnek",
                             "daouzek",
                             "trizek",
                             "pevarzek",
                             "pemzek",
                             "c'hwezek",
                             "seitek",
                             "triwec'h",
                             "naontek",
                             "ugent",
                             "unan warn-ugent",
                             "daou warn-ugent",
                             "tri warn-ugent",
                             "pevar warn-ugent",
                             "pemp warn-ugent",
                             "c'hwec'h warn-ugent",
                             "seizh warn-ugent",
                             "eizh warn-ugent",
                             "nav warn-ugent"};
inline constexpr Words hy = {
    "զրո",      "մեկ",      "երկու",   "երեք",    "չորս",      "հինգ",     "վեց",       "յոթ",
    "ութ",      "ինը",      "տասը",    "տասնմեկ", "տասներկու", "տասներեք", "տասնչորս",  "տասնհինգ",
    "տասնվեց",  "տասնյոթ",  "տասնութ", "տասնինը", "քսան",      "քսանմեկ",  "քսաներկու", "քսաներեք",
    "քսանչորս", "քսանհինգ", "քսանվեց", "քսանյոթ", "քսանութ",   "քսանինը"};
inline constexpr Words ka = {"ნული",     "ერთი",      "ორი",       "სამი",     "ოთხი",
                             "ხუთი",     "ექვსი",     "შვიდი",     "რვა",      "ცხრა",
                             "ათი",      "თერთმეტი",  "თორმეტი",   "ცამეტი",   "თოთხმეტი",
                             "თხუთმეტი", "თექვსმეტი", "ჩვიდმეტი",  "თვრამეტი", "ცხრამეტი",
                             "ოცი",      "ოცდაერთი",  "ოცდაორი",   "ოცდასამი", "ოცდაოთხი",
                             "ოცდახუთი", "ოცდაექვსი", "ოცდაშვიდი", "ოცდარვა",  "ოცდაცხრა"};
inline constexpr Words yi = {"נול",
                             "איינס",
                             "צוויי",
                             "דריי",
                             "פֿיר",
                             "פֿינף",
                             "זעקס",
                             "זיבן",
                             "אַכט",
                             "נײַן",
                             "צען",
                             "עלף",
                             "צוועלף",
                             "דרײַצן",
                             "פֿערצן",
                             "פֿופֿצן",
                             "זעכצן",
                             "זיבעצן",
                             "אַכצן",
                             "נײַנצן",
                             "צוואַנציק",
                             "איין און צוואַנציק",
                             "צוויי און צוואַנציק",
                             "דריי און צוואַנציק",
                             "פֿיר און צוואַנציק",
                             "פֿינף און צוואַנציק",
                             "זעקס און צוואַנציק",
                             "זיבן און צוואַנציק",
                             "אַכט און צוואַנציק",
                             "נײַן און צוואַנציק"};
} // namespace spoken_time::detail
