#!/usr/bin/env python3
"""Render or check Android translations and fastlane metadata without network access."""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'localization'
RES = ROOT / 'android/app/src/main/res'
META = ROOT / 'android/fastlane/metadata/android'
FIELDS = {'title': 30, 'short_description': 80, 'full_description': 4000}
FORMATS = re.compile(r'%\d+\$[sd]')


def fixed_label(key):
    return key.startswith(('color_', 'font_'))


# Google Play's documented listing locales, reviewed 2026-09-14:
# https://support.google.com/googleplay/android-developer/answer/9844778
PLAY_LOCALES = set('af sq am ar hy-AM az-AZ bn-BD eu-ES be bg my-MM ca zh-HK zh-CN zh-TW hr cs-CZ da-DK nl-NL en-AU en-CA en-US en-GB en-IN en-SG en-ZA et fil fi-FI fr-CA fr-FR gl-ES ka-GE de-DE el-GR gu iw-IL hi-IN hu-HU is-IS id it-IT ja-JP kn-IN kk km-KH ko-KR ky-KG lo-LA lv lt mk-MK ms-MY ms ml-IN mr-IN mn-MN ne-NP no-NO fa fa-AE fa-AF fa-IR pl-PL pt-BR pt-PT pa ro rm ru-RU sr si-LK sk sl es-419 es-ES es-US sw sv-SE ta-IN te-IN th tr-TR uk ur vi'.split())


def android_text(text):
    return escape(text.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n'))


def outputs():
    rows = json.loads((SOURCE / 'locales.json').read_text())
    native = set(re.findall(r'\{Language::\w+, "([^"]+)"', (ROOT / 'cpp-spoken-time/src/spoken_time.cpp').read_text()))
    if len(rows) != len(native) or native != {r['time_code'] for r in rows}:
        raise ValueError('Native time catalog changed: update localization/locales.json.')
    en = json.loads((SOURCE / 'en.json').read_text())
    default = {e.attrib['name']: (e.text or '') for e in ET.parse(RES / 'values/strings.xml').getroot() if e.attrib.get('translatable') != 'false'}
    if default != {key: text for key, text in en['strings'].items() if not fixed_label(key)}:
        raise ValueError('English resources and localization/en.json differ. Update the English source and translations together.')
    locales = {r['app_locale']: r['resource_directory'] for r in rows}
    locales.update({'bs': 'values-bs', 'sr': 'values-sr', 'sr-Latn': 'values-b+sr+Latn'})
    play = {r['play_locale']: r['app_locale'] for r in rows if r['play_locale']}
    play.update({'sr': 'sr', 'en-GB': 'en'})
    if set(play) - PLAY_LOCALES:
        raise ValueError('Unsupported Google Play locale: '+', '.join(sorted(set(play) - PLAY_LOCALES)))
    catalogs = {}
    out = {}
    for locale, directory in sorted(locales.items()):
        catalog = json.loads((SOURCE / f'{locale}.json').read_text())
        strings = catalog['strings']
        if strings.keys() != en['strings'].keys():
            raise ValueError(f'{locale}: missing or extra string keys')
        for key, text in strings.items():
            if fixed_label(key) and text != en['strings'][key]:
                raise ValueError(f'{locale}/{key}: color and font names must remain in English')
            if not text.strip() or sorted(FORMATS.findall(text)) != sorted(FORMATS.findall(en['strings'][key])):
                raise ValueError(f'{locale}/{key}: empty text or changed format placeholders')
            if re.search(r'\{\{|\}\}|\[\d{3}\]', text):
                raise ValueError(f'{locale}/{key}: untranslated marker')
            if 'Tijd' in en['strings'][key] and 'Tijd' not in text:
                raise ValueError(f'{locale}/{key}: brand name changed')
            if locale != 'en' and not fixed_label(key) and len(text) > 20 and text == en['strings'][key]:
                raise ValueError(f'{locale}/{key}: English sentence has not been translated')
        for field, limit in FIELDS.items():
            value = catalog['store'][field].strip()
            if not value or len(value.encode('utf-16-le')) // 2 > limit:
                raise ValueError(f'{locale}/{field}: empty or exceeds {limit} UTF-16 characters')
        if not catalog['store']['title'].startswith('Tijd'):
            raise ValueError(f'{locale}/title: retain the Tijd brand')
        catalogs[locale] = catalog
        if locale != 'en':
            xml = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/localization.py; edit localization/'+locale+'.json. -->\n<resources>\n'
            xml += ''.join(f'    <string name="{key}"'+(' formatted="false"' if '%' in value and not FORMATS.search(value) else '')+f'>{android_text(value)}</string>\n' for key, value in strings.items() if not fixed_label(key))
            out[RES / directory / 'strings.xml'] = xml + '</resources>\n'
    # Base-language fallback also works on Android 6 when a region is not listed.
    out[RES / 'values-pt/strings.xml'] = out[RES / 'values-b+pt+PT/strings.xml']
    for locale, source_locale in sorted(play.items()):
        store = catalogs[source_locale]['store']
        for field, limit in FIELDS.items():
            value = store[field].strip()
            length = len(value.encode('utf-16-le')) // 2
            if not value or length > limit:
                raise ValueError(f'{locale}/{field}: {length} characters, limit {limit}. Edit localization/{source_locale}.json.')
            if field == 'title' and not value.startswith('Tijd'):
                raise ValueError(f'{locale}/title: retain the Tijd brand')
            out[META / locale / (field+'.txt')] = value+'\n'
        out[META / locale / 'changelogs/default.txt'] = store['short_description'].strip()+'\n'
    xml = '<?xml version="1.0" encoding="utf-8"?>\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n'
    out[RES / 'xml/locales_config.xml'] = xml + ''.join(f'    <locale android:name="{locale}" />\n' for locale in sorted(locales)) + '</locale-config>\n'
    return out, len(locales), len(play)


def check_editorial_readiness():
    def content_hash(path):
        data = json.loads(path.read_text())
        content = {key: data[key] for key in ('strings', 'store')}
        return hashlib.sha256(json.dumps(content, ensure_ascii=False, sort_keys=True).encode()).hexdigest()

    review = json.loads((SOURCE / 'review.json').read_text())
    if review['source_sha256'] != content_hash(SOURCE / 'en.json'):
        raise ValueError('English source changed since editorial review. Reassess affected translations.')
    rows = json.loads((SOURCE / 'locales.json').read_text())
    required = {row['app_locale'] for row in rows} - {'en'} | {'bs', 'sr', 'sr-Latn'}
    pending = []
    for locale in sorted(required):
        entry = review['locales'].get(locale, {})
        if entry.get('status') != 'rewritten_context_reviewed' or entry.get('content_sha256') != content_hash(SOURCE / f'{locale}.json'):
            pending.append(locale)
    if pending:
        raise ValueError(f'{len(pending)} locales still need contextual retranslation/review: '+', '.join(pending)+'. See localization/RETRANSLATION.md. Structural checks do not establish translation quality.')


def main():
    parser = argparse.ArgumentParser(description=__doc__, epilog='Examples: python3 scripts/localization.py; python3 scripts/localization.py --check')
    parser.add_argument('--check', action='store_true', help='Check completeness, placeholders, Play limits and generated files without writing.')
    parser.add_argument('--for-upload', action='store_true', help='Also reject withdrawn or changed translations; read-only, implies --check.')
    args = parser.parse_args()
    args.check = args.check or args.for_upload
    try:
        files, apps, listings = outputs()
        stale = []
        for path, content in files.items():
            if args.check:
                if not path.exists() or path.read_text() != content:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
        expected = set(files)
        actual = set(META.rglob('*.txt')) | set(RES.glob('values-*/strings.xml'))
        extras = actual - expected
        if extras:
            raise ValueError('Unmapped generated files: '+', '.join(str(p.relative_to(ROOT)) for p in sorted(extras)))
        if stale:
            raise ValueError(f'{len(stale)} generated files missing or stale. Run python3 scripts/localization.py. First: {stale[0]}')
        if args.for_upload:
            check_editorial_readiness()
        print(f'{"Checked" if args.check else "Generated"} {apps} app locales and {listings} Play listings; structural checks only: keys, placeholders and field limits pass.')
    except (ValueError, OSError, KeyError, ET.ParseError) as error:
        print(f'Localization error: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
